name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: Luciano Pereira, lucianofullstack, lucianofullstack@users.noreply.github.com
          extras_css: |
            h1.field { color: #25d366!important }
            h2.field, h3.field { color: #969289!important }
            .field svg { fill:#969289!important}
            footer {display: none!important}
          token: ${{ secrets.METRICS_TOKEN }}
